# -*- coding: utf-8 -*-
"""pdf split(去除雜物)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pO989AEABVz-kxHqQj4YW40dYilpBZjO
"""

import PyPDF2
import json
import os
import re

def pdf_to_text(pdf_path):
    text = ""
    with open(pdf_path, "rb") as f:
        pdf_reader = PyPDF2.PdfReader(f)
        for page in pdf_reader.pages:
            # Extract text from page
            page_text = page.extract_text()
            # Remove footer
            page_text = re.sub(r'WWW\.SPCAPITALIQ\.COM.*?All Rights reserved\.', '', page_text, flags=re.DOTALL)
            # Remove text containing '[Operator Instructions]'
            #page_text = page_text.replace("[Operator Instructions]", "")
            page_text = page_text.replace("(Operator Instructions)", "")
            page_text = page_text.replace("Questions and Answers:","Operator")
            page_text = page_text.replace("\n", "")
            #page_text = page_text.replace("Copyright \u00a9 2018 S&P Global Market Intelligence, a division of S&P Global Inc. All Rights reserved.spglobal.com/marketintelligence", "")
            page_text = page_text.replace("\u2019", "'")
            page_text = page_text.replace("\u2014", "-")
            page_text = page_text.replace("\u2026", "...")
            page_text = page_text.replace("\u201d", " ")
            page_text = page_text.replace("\u201c", " ")
            #page_text = page_text.replace("TESLA, INC. FQ3 2018 EARNINGS CALL  OCT 24, 2018", "")
            # Remove text between "TESLA" and "2015"
            text += page_text

    # Remove text before first "Presentation"
    text = text.split('Martin Viecha: ', 1)[-1]
    return text

def split_text_by_operator(text):
    paragraphs = text.split('Martin Viecha: ')
    # Remove leading and trailing whitespace from each paragraph
    paragraphs = [p.strip() for p in paragraphs]
    # Remove empty paragraphs
    paragraphs = [p for p in paragraphs if p]
    # Remove the last paragraph
    if paragraphs:
        paragraphs.pop()  # Remove the last paragraph
    # Add numbering to paragraphs
    numbered_paragraphs = [{"paragraph": p} for p in paragraphs]
    return numbered_paragraphs


def main():
    pdf_path = "/Users/xuzhiwei/GDSC-ai-stock/PDF/2024Q1.pdf"
    text = pdf_to_text(pdf_path)
    paragraphs = split_text_by_operator(text)

    # Remove "\n" from each paragraph
    for paragraph in paragraphs:
        for key, value in paragraph.items():
            paragraph[key] = value.replace("\n", "")
            paragraph[key] = value.replace("\u00e9", "")

    with open("/Users/xuzhiwei/GDSC-ai-stock/Data/split/2024Q1_split.json", "w") as f:
        json.dump(paragraphs, f, indent=4)


if __name__ == "__main__":
    main()