# -*- coding: utf-8 -*-
"""earnings_call

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rXMxpqH3TMTnmRNfQrmRx0V5ZvG9SFiq
"""

pip install PyPDF2

import PyPDF2
import json
import os
import re
import requests
from google.colab import files

def pdf_to_text(pdf_path):
    text = ""
    with open(pdf_path, "rb") as f:
        pdf_reader = PyPDF2.PdfReader(f)
        for page in pdf_reader.pages:

            page_text = page.extract_text()
            # 去除頁尾的文字
            page_text = re.sub(r'WWW\.SPCAPITALIQ\.COM.*?All Rights reserved\.', '', page_text, flags=re.DOTALL)
            text += page_text

    # 從"Presentation"開始讀
    text = text.split('Presentation', 1)[-1]
    return text

# 把earnings call的pdf切割
def split_text_by_operator(text):
    paragraphs = text.split('Operator')
    # 用Operator作為議題的分界
    paragraphs = [p.strip() for p in paragraphs]
    paragraphs = [p for p in paragraphs if p]
    # 編號paragraphs
    numbered_paragraphs = [{"paragraph" + str(i + 1): p} for i, p in enumerate(paragraphs)]
    return numbered_paragraphs

def main(pdf_path):
    filename = os.path.basename(pdf_path)
    text = pdf_to_text(pdf_path)
    paragraphs = split_text_by_operator(text)
    paragraphs.insert(0, {"filename": filename})
    with open(os.path.join(output_folder, filename.replace(".pdf", "_split.json")), "w") as f:
        json.dump(paragraphs, f, indent=4)

def query(payload):
    response = requests.post(API_URL, headers=headers, json=payload)
    return response.json()

API_URL = "https://api-inference.huggingface.co/models/facebook/bart-large-cnn"
headers = {"Authorization": "Bearer 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"}

print("choose pdf file:")
uploaded = files.upload()

output_folder = "output_folder"

os.makedirs(output_folder, exist_ok=True)

for input_file in uploaded.keys():
    main(input_file)
    print(f"{input_file} finish")

    output_file = os.path.join(output_folder, os.path.basename(input_file).replace(".pdf", "_split.json"))

    with open(output_file, "r") as file:
        data = json.load(file)

    output_data = []

    paragraph_number = 0

    for item in data:
        for key, value in item.items():
            if key.startswith("paragraph"):
                paragraph_number += 1  # 原本想作編號但好像沒用到
                paragraph_text = value

                result = query({"inputs": paragraph_text})

                summary_text = ["summary_text"]
                #summary_text = result[0]["summary_text"]

                # 寫入
                output_data.append({"paragraph": paragraph_text, "summary_text": summary_text})

    output_file = os.path.join(output_folder, os.path.basename(input_file).replace(".pdf", "_summarize.json"))
    with open(output_file, "w") as file:
        json.dump(output_data, file, indent=4)

    print(f"finish writing into {output_file}")